version: '3.8'

services:
  claude-base:
    build:
      context: containers
      dockerfile: Dockerfile
    image: claude-code-base:latest
    volumes:
      - ./workspace:/workspace
      - ~/.ssh:/tmp/ssh_key:ro
    environment:
      - GIT_USER_NAME=${GIT_USER_NAME:-Claude Docker User}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-claude-docker@example.com}
      - CLAUDE_YOLO_MODE=${CLAUDE_YOLO_MODE:-false}
      - GIT_REPO_URL=${GIT_REPO_URL:-}
      - GIT_HOST_DOMAIN=${GIT_HOST_DOMAIN:-}
    stdin_open: true
    tty: true

  claude-python:
    build:
      context: containers/python
      dockerfile: Dockerfile
    image: claude-code-python:latest
    depends_on:
      - claude-base
    volumes:
      - ./workspace:/workspace
      - ~/.ssh:/tmp/ssh_key:ro
    environment:
      - GIT_USER_NAME=${GIT_USER_NAME:-Claude Docker User}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-claude-docker@example.com}
      - CLAUDE_YOLO_MODE=${CLAUDE_YOLO_MODE:-false}
      - GIT_REPO_URL=${GIT_REPO_URL:-}
      - GIT_HOST_DOMAIN=${GIT_HOST_DOMAIN:-}
    stdin_open: true
    tty: true