version: '3.8'

services:
  claude-base:
    build:
      context: containers
      dockerfile: Dockerfile
    image: claude-code-base:latest
    volumes:
      - ${CLAUDE_CONFIG_DIR:-~/.claude-code-container}:/home/node
      - ${WORKSPACE_DIR:-./workspace}:/workspace
      - ${SSH_KEY_DIR:-~/.ssh}:/tmp/ssh_key:ro
    environment:
      - GIT_USER_NAME
      - GIT_USER_EMAIL
      - CLAUDE_YOLO_MODE
      - GIT_REPO_URL
      - GIT_HOST_DOMAIN
      - WORKSPACE_DIR
      - SSH_KEY_DIR
      - GH_TOKEN
    stdin_open: true
    tty: true

  claude-python:
    build:
      context: containers/python
      dockerfile: Dockerfile
    image: claude-code-python:latest
    depends_on:
      - claude-base
    volumes:
      - ${CLAUDE_CONFIG_DIR:-~/.claude-code-container}:/home/node
      - ${WORKSPACE_DIR:-./workspace}:/workspace
      - ${SSH_KEY_DIR:-~/.ssh}:/tmp/ssh_key:ro
    environment:
      - GIT_USER_NAME
      - GIT_USER_EMAIL
      - CLAUDE_YOLO_MODE
      - GIT_REPO_URL
      - GIT_HOST_DOMAIN
      - WORKSPACE_DIR
      - SSH_KEY_DIR
      - GH_TOKEN
    stdin_open: true
    tty: true